# Generated by Django 5.2.1 on 2025-05-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rent_created_at_rent_deleted_at_rent_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
