# Generated by Django 5.2.1 on 2025-05-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_address_alter_rent_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'street'), name='unique_address'),
        ),
    ]
