# Generated by Django 5.2.1 on 2025-05-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_address_unique_address'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'street', 'apartment_number'), name='unique_address_with_apartment'),
        ),
    ]
